# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

dist: xenial
addons:
  apt:
    packages:
      - libudunits2-dev
      - libhdf5-dev

bioc_packages:
  - SingleCellExperiment

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install()'
  - Rscript -e 'pkgdown::build_site()'
  - ls -l

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  local-dir: docs
  on:
    branch: develop
  verbose: true

notifications:
  email:
    on_success: change
    on_failure: change
