# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

dist: xenial
addons:
  apt:
    packages:
      - libudunits2-dev
      - libhdf5-dev

bioc_packages:
  - SingleCellExperiment

after_success:
  - Rscript -e 'covr::codecov()'

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: change
